export const navigation = [
  { section: 'Centro operacional' },
  { path: '/dashboard', label: 'Visão operacional', icon: 'dashboard' },
  { path: '/calendario', label: 'Calendário', icon: 'calendar' },
  { path: '/tecnicos', label: 'Técnicos', icon: 'users' },
  { path: '/mapa-pa', label: 'Mapa de PA', icon: 'building' },
  { section: 'Pausas e aprovações' },
  { path: '/pausas', label: 'Pausas', icon: 'pause', permission: 'pausas.use' },
  { path: '/metricas', label: 'Métricas', icon: 'chart', permission: 'metricas.read' },
  { path: '/admin', label: 'Aprovações e admin', icon: 'shield', permission: 'operacao.approve' },
  { section: 'Escalas' },
  { path: '/escala-turnos', label: 'Escalas de Sábado', icon: 'clock' },
  { path: '/escala-presencial', label: 'Escala presencial', icon: 'building' },
  { path: '/ausencias', label: 'Ausências', icon: 'userMinus' },
  { path: '/plantonistas', label: 'Plantonistas', icon: 'phone' },
  { path: '/sobreavisos', label: 'Sobreavisos', icon: 'radio' },
  { section: 'Fluxos operacionais' },
  { path: '/horas-extras', label: 'Horas extras', icon: 'timer' },
  { path: '/correcao-ponto', label: 'Correção de ponto', icon: 'edit' },
  { path: '/avisos', label: 'Avisos', icon: 'bell' },
  { path: '/chamados-criticos', label: 'Chamados críticos', icon: 'alert' },
  { section: 'Conhecimento e plataforma' },
  { path: '/documentacao', label: 'Documentação', icon: 'book' },
  { path: '/relatorios', label: 'Relatórios', icon: 'file', permission: 'relatorios.read' },
  { path: '/configuracoes', label: 'Configurações', icon: 'settings', permission: 'configuracoes.manage' },
  { path: '/integracoes', label: 'Integrações', icon: 'plug', permission: 'integracoes.manage' },
]

export const pageMetadata = {
  '/dashboard': ['Visão operacional', 'Acompanhe o estado do portal e da equipe.'],
  '/pausas': ['Pausas', 'Controle de pausas e disponibilidade em tempo real.'],
  '/admin': ['Administração', 'Aprovações, funcionários, usuários e segurança.'],
  '/metricas': ['Métricas', 'Indicadores e histórico de pausas.'],
  '/calendario': ['Calendário', 'Eventos, escalas e janelas operacionais.'],
  '/tecnicos': ['Técnicos', 'Diretório operacional da equipe.'],
  '/escala-turnos': ['Escalas de Sábado', 'Publicações da escala de sábado disponíveis para consulta da equipe.'],
  '/escala-presencial': ['Escala presencial', 'Presença por data, equipe e colaborador.'],
  '/ausencias': ['Ausências', 'Férias, atestados, treinamentos e folgas.'],
  '/horas-extras': ['Horas extras', 'Solicitações e aprovações de horas adicionais.'],
  '/correcao-ponto': ['Correção de ponto', 'Solicitações de ajuste de marcação.'],
  '/avisos': ['Avisos', 'Comunicados operacionais e de segurança.'],
  '/plantonistas': ['Plantonistas', 'Contatos e horários dos plantões ativos.'],
  '/sobreavisos': ['Sobreavisos', 'Cobertura de sobreaviso ativa e planejada.'],
  '/mapa-pa': ['Mapa de PA', 'Alocacao visual de posicoes fisicas por data.'],
  '/chamados-criticos': ['Chamados críticos', 'War rooms, impacto, mitigação e resolução de crises.'],
  '/documentacao': ['Documentação', 'WIs, IOPs, runbooks e checklists.'],
  '/relatorios': ['Relatórios', 'Relatórios operacionais e auditoria.'],
  '/configuracoes': ['Configurações', 'Preferências e informações de segurança.'],
  '/integracoes': ['Integrações', 'Estado das conexões com plataformas externas.'],
}
